# Generated by Django 2.2.1 on 2019-05-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Motor de Búsqueda',
                'verbose_name_plural': 'Motores de Búsqueda',
                'db_table': 'engine',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.URLField(verbose_name='URL')),
                ('frecuency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=7, verbose_name='Frecuencia')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_engine', to='app_seo_tool.Engine', verbose_name='Motor de Búsqueda')),
            ],
            options={
                'verbose_name': 'Busqueda',
                'verbose_name_plural': 'Busquedas',
                'db_table': 'search',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('url', models.URLField(verbose_name='URL')),
                ('position', models.PositiveIntegerField(verbose_name='Posicion')),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_search', to='app_seo_tool.Search', verbose_name='Búsqueda')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'db_table': 'result',
            },
        ),
    ]
