# Generated by Django 2.2.1 on 2019-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seo_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='keywords',
            field=models.CharField(max_length=100, verbose_name='Palabras Clave'),
        ),
    ]
